language: go
sudo: false
env:
  - GO111MODULE=on
go:
  - 1.13.x
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode11.3
    - os: windows
before_script:
  - go mod tidy
  - mkdir -p bin
  - FILE_NAME="$TRAVIS_OS_NAME"
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then FILE_NAME=win64.exe ; fi
script:
  - go build -o bin/boltd-"$FILE_NAME" cmd/boltd/server.go
  - ls -alh ./
  - ls -alh bin
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
deploy:
  provider: releases
  api_key:
    secure: s52jeH3i3rTgMcf/yoKOSAl4AifrqXcoSWa5ohkJYC47WyoO7q2fZlQxETmWbm08piALgfOjkn6vsdQF2qnLJPcMLFGkDbQGvSbHUmrF2QfiCXdOJ3cL5lkt8mpi3X0HU4RWv9Uh09w9k/PY0INzS2VAgH1eqvNTPclFbViyj2retblO6pC5GUHJEQ1/Q8rA6RfuXycuQBGzNVH2FWf+G+c4NSbtRD2TKLfM4MlFU2wMpAczFE/ffHSV4SRtGAWlU+MWFaaCrCAB/agbqIS06CCDQuo4EuwZDYBIRIHrfZG7hUDsPHRGSYKA7Yn5s0vLh06wLPR8gsFjEqPpaE5cI1p3PDNENKmH74ifVjbCt03bvEcSSeVwKriD2toHO71oujvunoYeju9LI+Bi4um2SJ6uAK8r/gulvMkldfPsiRiFn2V5gYpt6Yf6myMbpT7a5UD0huF4I7fUD5nOTsCicqfprRAn1apD8zOzKRxsHRvt01hDum35BgVWgt7CN4nIot+CvTTgtnsitFrAolZ7F7Z6JKZIMHPZN9Ae/bIPHo91h3poKEgC/Uk9Uw7Qg2N0TtBEQyQuHhtns+i3YhYHMHnWbSZxbL6j9UpYkirtC03+XKsITdDeUsZG3fRmThFPZR6KwOeXTmvm6V8nLr3YFG5uXWPOBeOkU+j5rg4ha7o=
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: DGHeroin/boltdbr
    tags: true